sudo: false
cache: bundler
language: ruby
bundler_args: --without local_development
script:
- bundle exec rake
- bundle exec ataru check
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - rbx-2
  - ruby-head
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='--2.0 --server -Xcompile.invokedynamic=false'
    - rvm: jruby-head
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
  allow_failures:
    - rvm: jruby
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true
notifications:
  email:
    - timo.roessner@googlemail.com
    - matijs@matijs.net
    - chastell@chastell.net
  irc: irc.freenode.org#reek
